// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnjrldezxnhhdzebudyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuanJsZGV6eG5oaGR6ZWJ1ZHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTYyMDUsImV4cCI6MjA2MDAzMjIwNX0.DMHxLf0h1sY7c0SUQNw6qkqGgAOKxXpuplBm5njD7ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);